---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: ansible-nas
ansible_nas_timezone: Etc/UTC

## Enable some applications
heimdall_enabled: true
portainer_enabled: true
plex_enabled: true
homeassistant_enabled: true
esphome_enabled: true




### group_vars/all.yml overrides

###
### General
###

# Will be added to the docker group to give user command line access to docker
ansible_nas_user: james

# Your email and domain, used for Let's Encrypt SSL certs
ansible_nas_email: me@example.com

# Applications will have subdomain SSL certificates created if Traefik is enabled, e.g. ansible-nas.<your-domain>, nextcloud.<your-domain>
ansible_nas_domain: jgnet.com

# What version of python ansible should use on target system (path to spesific binary)
ansible_python_interpreter: /usr/bin/python3


###
### Samba
###
# The location where all shares will be created by default. Can be overridden on a per-share basis.
# This path will be mounted to backup containers, Duplicati
samba_shares_root: /samba/shares

# Shares you want published over Samba.
samba_shares:
  - name: downloads
    comment: "Stuff downloaded"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ downloads_root }}"

  - name: movies
    comment: "Movies"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ movies_root }}"

  - name: tv
    comment: "TV Episodes"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ tv_root }}"

  - name: music
    comment: "Music"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ music_root }}"

  # - name: podcasts
  #   comment: "Podcasts"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: "{{ podcasts_root }}"

  - name: dump
    comment: "File dump"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ samba_shares_root }}/dump"

  # - name: games
  #   comment: "Games"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: "{{ samba_shares_root }}/games"

  - name: photos
    comment: "Pictures"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ photos_root }}"

  # - name: books
  #   comment: "Books"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: "{{ books_root }}"

  # - name: audiobooks
  #   comment: "Audiobooks"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browsable: yes
  #   path: "{{ audiobooks_root }}"

  # - name: comics
  #   comment: "Comics"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: "{{ comics_root }}"

  - name: documents
    comment: "Documents"
    guest_ok: yes
    public: yes
    writable: yes
    browseable: yes
    path: "{{ documents_root }}"

  # - name: code
  #   comment: "Code"
  #   guest_ok: yes
  #   public: yes
  #   writable: yes
  #   browseable: yes
  #   path: "{{ code_root }}"


###
### NFS
###
# Data you want published over NFS. More info on the NFS config format can be found at
# https://help.ubuntu.com/community/SettingUpNFSHowTo#Shares
# WARNING: Weird things might happen if you share the same data over Samba and NFS and allow writes on both!

nfs_shares_root: /nfs/shares

nfs_exports:
  - "{{ nfs_shares_root }}/public *(rw,sync,no_root_squash)"